# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed1ef63e02eeaf980d81848a8e5a391f8d6bb0f6686d51da9934b20c962ef638e85fa1b69600867abb08b2abc1593d9413b80419003b77d05305deee70b2988a

test:
  secret_key_base: 9ffd0fe2e93cf91c70fde28770770e018192ef2bc374f12c0d58c96978adb7196f1b6530397c7e15564b33f08238698318209925e3626cfcb31471aa3c622649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
